export const actionType = {
    SET_DARK_MODE: 'SET_DARK_MODE',
    SET_STATE_LOGIN: 'SET_STATE_LOGIN',
    SET_LOGOUT: 'SET_LOGOUT',
    SCROLLINTOVIEW: 'SCROLLINTOVIEW',

    SET_PLAY_A_VIDEO: 'SET_PLAY_A_VIDEO',

    SIGN_WITH_USERNAME: 'SIGN_WITH_USERNAME',

    SET_MONTH: 'SET_MONTH',
    SET_DAY: 'SET_DAY',
    SET_YEAR: 'SET_YEAR',
};
