export const actionType = {
    SET_DARK_MODE: 'SET_DARK_MODE',
    SET_STATE_LOGIN: 'SET_STATE_LOGIN',
    SET_OPEN_EDIT: 'SET_OPEN_EDIT',
    SET_LOGOUT: 'SET_LOGOUT',
    SCROLLINTOVIEW: 'SCROLLINTOVIEW',

    SET_PLAY_A_VIDEO: 'SET_PLAY_A_VIDEO',

    SIGN_WITH_USERNAME: 'SIGN_WITH_USERNAME',
    LOGIN_WITH_USERNAME: 'LOGIN_WITH_USERNAME',
    SET_ISLOGIN: 'SET_ISLOGIN',

    SET_MONTH: 'SET_MONTH',
    SET_DAY: 'SET_DAY',
    SET_YEAR: 'SET_YEAR',

    SET_USER: 'SET_USER',

    SET_LOGIN: 'SET_LOGIN',
    SET_PROFILE_MODE: 'SET_PROFILE_MODE',

    SET_TOKEN: 'SET_TOKEN',
    SET_INIT_USER: 'SET_IMAGE_USER',
    SET_CUR_PROFLE: 'SET_CUR_PROFLE',

    SET_EDIT_AVATAR_PROFILE: 'SET_EDIT_AVATAR_PROFILE',
    SET_AVATAR_EDITED: 'SET_AVATAR_EDITED',

    SET_LOGIN_LOAIDNG: 'SET_LOGIN_LOAIDNG',

    SET_LOADING_UPDATE_PROFILE: 'SET_LOADING_UPDATE_PROFILE',
};
